#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT_DIR
readonly DIST_DIR="${ROOT_DIR}/dist"
readonly GENERATED_NOTICE="# Generated by scripts/bundle.sh. Do not edit; update modular sources instead."

bundle_entrypoint() {
    local entrypoint="$1"
    local output="$2"
    local input_path="${ROOT_DIR}/${entrypoint}"
    local output_path="${DIST_DIR}/${output}"

    if [[ ! -f "$input_path" ]]; then
        echo "Missing entrypoint: $entrypoint" >&2
        return 1
    fi

    mkdir -p "$DIST_DIR"

    local source_re='^[[:space:]]*source[[:space:]]+"\$\{SCRIPT_DIR\}/([^"]+)"[[:space:]]*$'
    local shellcheck_source_re='^[[:space:]]*#[[:space:]]*shellcheck[[:space:]]+source='
    local script_dir_re='^[[:space:]]*SCRIPT_DIR="\$\(cd "\$\(dirname "\$\{BASH_SOURCE\[0\]\}"\)" && pwd\)"[[:space:]]*$'
    local pending_shellcheck_line=""
    local bundled_any=0
    local line

    : > "$output_path"

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ $line =~ $shellcheck_source_re ]]; then
            pending_shellcheck_line="$line"
            continue
        fi

        if [[ $line =~ $source_re ]]; then
            local module_path="${BASH_REMATCH[1]}"
            local module_file="${ROOT_DIR}/${module_path}"

            if [[ ! -f "$module_file" ]]; then
                echo "Missing sourced module: $module_path" >&2
                return 1
            fi

            {
                printf '\n# --- Begin inlined %s ---\n' "$module_path"
                sed '1{/^# shellcheck shell=bash$/d;}' "$module_file"
                printf '\n# --- End inlined %s ---\n' "$module_path"
            } >> "$output_path"
            pending_shellcheck_line=""
            bundled_any=1
            continue
        fi

        if [[ -n $pending_shellcheck_line ]]; then
            printf '%s\n' "$pending_shellcheck_line" >> "$output_path"
            pending_shellcheck_line=""
        fi

        if [[ $line =~ $script_dir_re ]]; then
            printf '%s\n' "$GENERATED_NOTICE" >> "$output_path"
            continue
        fi

        printf '%s\n' "$line" >> "$output_path"
    done < "$input_path"

    if [[ -n $pending_shellcheck_line ]]; then
        printf '%s\n' "$pending_shellcheck_line" >> "$output_path"
    fi

    if [[ $bundled_any -ne 1 ]]; then
        echo "No source lines were bundled from $entrypoint" >&2
        return 1
    fi

    chmod +x "$output_path"
    echo "Bundled $entrypoint -> ${output_path#"$ROOT_DIR/"}"
}

bundle_powershell_entrypoint() {
    local entrypoint="$1"
    local output="$2"
    local input_path="${ROOT_DIR}/${entrypoint}"
    local output_path="${DIST_DIR}/${output}"

    if [[ ! -f "$input_path" ]]; then
        echo "Missing entrypoint: $entrypoint" >&2
        return 1
    fi

    mkdir -p "$DIST_DIR"

    local dot_source_re='^[[:space:]]*\.[[:space:]]+\(Join-Path[[:space:]]+[$]ScriptRoot[[:space:]]+'"'"'([^'"'"']+)'"'"'\)[[:space:]]*$'
    local script_root_re='^[[:space:]]*[$]ScriptRoot[[:space:]]*=[[:space:]]*Split-Path[[:space:]]+-Parent[[:space:]]+[$]MyInvocation\.MyCommand\.Path[[:space:]]*$'
    local bundled_any=0
    local line

    : > "$output_path"

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ $line =~ $script_root_re ]]; then
            printf '%s\n' "$GENERATED_NOTICE" >> "$output_path"
            continue
        fi

        if [[ $line =~ $dot_source_re ]]; then
            local module_path="${BASH_REMATCH[1]}"
            local module_file="${ROOT_DIR}/${module_path}"

            if [[ ! -f "$module_file" ]]; then
                echo "Missing dot-sourced module: $module_path" >&2
                return 1
            fi

            {
                printf '\n# --- Begin inlined %s ---\n' "$module_path"
                cat "$module_file"
                printf '\n# --- End inlined %s ---\n' "$module_path"
            } >> "$output_path"
            bundled_any=1
            continue
        fi

        printf '%s\n' "$line" >> "$output_path"
    done < "$input_path"

    if [[ $bundled_any -ne 1 ]]; then
        echo "No dot-source lines were bundled from $entrypoint" >&2
        return 1
    fi

    chmod +x "$output_path"
    echo "Bundled $entrypoint -> ${output_path#"$ROOT_DIR/"}"
}

main() {
    bundle_entrypoint "intruder-hunter.sh" "intruder-hunter.sh"
    bundle_entrypoint "intruder-hunter-macos.sh" "intruder-hunter-macos.sh"
    bundle_powershell_entrypoint "intruder-hunter.ps1" "intruder-hunter.ps1"
}

main "$@"
